/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "main.h"
#include "experiment.h"
#include "stdio.h"
#include "FreeRTOS.h"
#include "task.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0   (GUI_ID_USER + 0x00)
#define ID_BUTTON_GET (GUI_ID_USER + 0x01)
#define ID_BUTTON_PUT (GUI_ID_USER + 0x02)
#define ID_BUTTON_RETURN (GUI_ID_USER + 0x03)
#define ID_PROGBAR_0 (GUI_ID_USER + 0x04)
#define ID_BUTTON_START_NO3 (GUI_ID_USER + 0x05)
#define ID_TEXT_NO3ND (GUI_ID_USER + 0x06)
#define ID_TEXT_NO3YL (GUI_ID_USER + 0x07)
#define ID_TEXT_DJDW (GUI_ID_USER + 0x08)
#define ID_BUTTON_START_TEST (GUI_ID_USER + 0x09)
#define ID_BUTTON_START_BLOCK (GUI_ID_USER + 0x0A)
#define ID_TEXT_RYCL (GUI_ID_USER + 0x0B)
#define ID_BUTTON_CLEAR (GUI_ID_USER + 0x0C)
#define ID_TEXT_5 (GUI_ID_USER + 0x0E)
#define ID_PROGBAR_TEST (GUI_ID_USER + 0x0F)
#define ID_GRAPH_0   (GUI_ID_USER + 0x10)

// USER START (Optionally insert additional defines)
extern const GUI_FONT GUI_FontHZ_Consolas;
extern const GUI_FONT GUI_FontHZ_Arial;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/


// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    {WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
    {BUTTON_CreateIndirect, "ÎüÒº", ID_BUTTON_GET, 180, 425, 100, 50, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "ÅÅÒº", ID_BUTTON_PUT, 330, 425, 100, 50, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "ÇåÏ´", ID_BUTTON_CLEAR, 480, 425, 100, 50, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "²Ëµ¥", ID_BUTTON_RETURN, 585, 5, 210, 50, 0, 0x0, 0},
    {PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 5, 450, 150, 25, 0, 0x0, 0},
    {TEXT_CreateIndirect, "AgNO3Å¨¶È", ID_TEXT_NO3ND, 5, 5, 160, 32, 0, 0x64, 0},
    {TEXT_CreateIndirect, "AgNO3ÓÃÁ¿", ID_TEXT_NO3YL, 5, 45, 160, 32, 0, 0x64, 0},
    {TEXT_CreateIndirect, "µç¼«µçÎ»", ID_TEXT_DJDW, 5, 85, 130, 32, 0, 0x64, 0},
    {BUTTON_CreateIndirect, "¿Õ°×ÊµÑé", ID_BUTTON_START_BLOCK, 585, 240, 210, 60, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "AgNO3¼ì²â", ID_BUTTON_START_NO3, 585, 130, 210, 60, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "ÂÈÀë×Ó¼ì²â", ID_BUTTON_START_TEST, 585, 350, 210, 60, 0, 0x0, 0},
    
    {TEXT_CreateIndirect, "ÈÜÒº´æÁ¿", ID_TEXT_RYCL, 20, 415, 120, 35, 0, 0x64, 0},
    { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 5, 130, 575, 280, 0, 0x0, 0 },
    // USER START (Optionally insert additional widgets)
    // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
static struct exper_msg msg;
static uint8_t put_func = 0;
// USER START (Optionally insert additional static code)
GRAPH_SCALE_Handle hScaleV, hScaleH;
GRAPH_DATA_Handle pdataGRP;
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    int NCode;
    int Id, i;
    struct exper_msg *priv;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Framewin'
        //
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_GRAY);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_GET);
        BUTTON_SetFont(hItem, &GUI_FontHZ_Consolas);
        BUTTON_SetTextColor(hItem, 0, GUI_BLUE);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PUT);
        BUTTON_SetFont(hItem, &GUI_FontHZ_Consolas);
        BUTTON_SetTextColor(hItem, 0, GUI_BLUE);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CLEAR);
        BUTTON_SetFont(hItem, &GUI_FontHZ_Consolas);
        BUTTON_SetTextColor(hItem, 0, GUI_BLUE);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RETURN);
        BUTTON_SetFont(hItem, &GUI_FontHZ_Consolas);
        BUTTON_SetTextColor(hItem, 0, GUI_RED);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_START_BLOCK);
        BUTTON_SetFont(hItem, &GUI_FontHZ_Consolas);
        BUTTON_SetTextColor(hItem, 0, GUI_BLUE);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_START_NO3);
        BUTTON_SetFont(hItem, &GUI_FontHZ_Consolas);
        BUTTON_SetTextColor(hItem, 0, GUI_BLUE);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_START_TEST);
        BUTTON_SetFont(hItem, &GUI_FontHZ_Consolas);
        BUTTON_SetTextColor(hItem, 0, GUI_BLUE);
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_NO3ND);
        TEXT_SetFont(hItem, &GUI_FontHZ_Consolas);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_NO3YL);
        TEXT_SetFont(hItem, &GUI_FontHZ_Consolas);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_DJDW);
        TEXT_SetFont(hItem, &GUI_FontHZ_Consolas);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RYCL);
        TEXT_SetFont(hItem, &GUI_FontHZ_Consolas);
        TEXT_SetTextColor(hItem, GUI_BLACK);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
        PROGBAR_SetFont(hItem, GUI_FONT_24B_ASCII);
        PROGBAR_SetBarColor(hItem, 0, GUI_GREEN);
        PROGBAR_SetMinMax(hItem, 0, 100);
        

        hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
        GRAPH_SetBorder(hItem, 40, 3, 3, 30);
        GRAPH_SetGridVis(hItem, 2);
        GRAPH_SetGridFixedX(hItem, 2);
        GRAPH_SetGridDistY(hItem, 20);
        GRAPH_SetGridDistX(hItem, 50);
        hScaleV = GRAPH_SCALE_Create(3, GUI_TA_LEFT, GRAPH_SCALE_CF_VERTICAL, 25);
        GRAPH_SCALE_SetTextColor(hScaleV, GUI_RED);
        GRAPH_AttachScale(hItem, hScaleV);
        hScaleH = GRAPH_SCALE_Create(260, GUI_TA_HCENTER, GRAPH_SCALE_CF_HORIZONTAL, 50);
        GRAPH_SCALE_SetTextColor(hScaleH, GUI_DARKGREEN);
        GRAPH_AttachScale(hItem, hScaleH);
        pdataGRP = GRAPH_DATA_YT_Create(GUI_GREEN, 500, 0, 0);
        GRAPH_AttachData(hItem, pdataGRP);
        GRAPH_DATA_YT_SetOffY(pdataGRP, 20);
        GRAPH_DATA_YT_SetAlign(pdataGRP, GRAPH_ALIGN_LEFT);
        GRAPH_DATA_YT_Clear(pdataGRP);
        // USER END
        break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_BUTTON_GET: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
                for (i = 0; i <= 100; i++) {
                    PROGBAR_SetValue(hItem, i);
                    WM_Exec();
                    vTaskDelay(50);
                }
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_PUT: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PUT);
                if (put_func) {    
                    BUTTON_SetText(hItem, "ÅÅÒº");
                    BUTTON_SetTextColor(hItem, 0, GUI_BLUE);
                    put_func = 0;
                } else {
                    BUTTON_SetText(hItem, "Í£Ö¹");
                    BUTTON_SetTextColor(hItem, 0, GUI_RED);
                    
                    hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
                    for (i = 100; i >= 0; i--) {
                        PROGBAR_SetValue(hItem, i);
                        WM_Exec();
                        vTaskDelay(50);
                    }
                    put_func = 1;
                }
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_RETURN: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                printf("run main menu\r\n");
                g_ui_msg.msg = MSG_LOAD_UI_MENU;
                GUI_EndDialog(pMsg->hWin, 0);
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_START_BLOCK: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_START_BLOCK);
                BUTTON_SetText(hItem, "Í£Ö¹ÊµÑé");
                msg.msg = EXPER_MSG_START;
                exper_msg_set(&msg);
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
    case WM_USER:
        priv = (struct exper_msg *)pMsg->Data.p;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_TEST);
        PROGBAR_SetValue(hItem, priv->progress);
        GRAPH_DATA_YT_AddValue(pdataGRP, (I16)(priv->progress & 0xffff));
        WM_Exec();
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/

WM_HWIN ui_blocktest_creat(void)
{
    g_ui_msg.hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    GUI_ExecCreatedDialog(g_ui_msg.hWin);
    return g_ui_msg.hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
