/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "main.h"
#include "experiment.h"
#include "stdio.h"
#include "FreeRTOS.h"
#include "task.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0   (GUI_ID_USER + 0x00)
#define ID_BUTTON_GET (GUI_ID_USER + 0x01)
#define ID_BUTTON_PUT (GUI_ID_USER + 0x02)
#define ID_BUTTON_RETURN (GUI_ID_USER + 0x03)
#define ID_PROGBAR_0 (GUI_ID_USER + 0x04)
#define ID_TEXT_0 (GUI_ID_USER + 0x05)
#define ID_TEXT_1 (GUI_ID_USER + 0x06)
#define ID_TEXT_2 (GUI_ID_USER + 0x07)
#define ID_TEXT_3 (GUI_ID_USER + 0x08)
#define ID_BUTTON_START (GUI_ID_USER + 0x0A)
#define ID_TEXT_4 (GUI_ID_USER + 0x0B)
#define ID_TEXT_5 (GUI_ID_USER + 0x0E)
#define ID_PROGBAR_TEST (GUI_ID_USER + 0x0F)
#define ID_GRAPH_0   (GUI_ID_USER + 0x10)

// USER START (Optionally insert additional defines)
extern const GUI_FONT GUI_FontHZ_Consolas;
extern const GUI_FONT GUI_FontHZ_Arial;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/


// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
    {BUTTON_CreateIndirect, "Button", ID_BUTTON_GET, 639, 103, 140, 40, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "Button", ID_BUTTON_PUT, 638, 189, 140, 40, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "Button", ID_BUTTON_RETURN, 632, 370, 140, 40, 0, 0x0, 0},
    {PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 640, 17, 140, 40, 0, 0x0, 0},
    {TEXT_CreateIndirect, "Text", ID_TEXT_0, 5, 5, 160, 35, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text", ID_TEXT_1, 5, 45, 160, 35, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text", ID_TEXT_2, 5, 85, 160, 35, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text", ID_TEXT_3, 5, 125, 130, 35, 0, 0x64, 0},
    {BUTTON_CreateIndirect, "Button", ID_BUTTON_START, 5, 350, 215, 60, 0, 0x0, 0},
    {TEXT_CreateIndirect, "Text", ID_TEXT_4, 530, 25, 130, 35, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text", ID_TEXT_5, 240, 380, 130, 35, 0, 0x0, 0},
    {PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_TEST, 340, 378, 200, 30, 0, 0x0, 0},
    { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 5, 160, 540, 180, 0, 0x0, 0 },
    // USER START (Optionally insert additional widgets)
    // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
static struct exper_msg msg;

// USER START (Optionally insert additional static code)
GRAPH_SCALE_Handle hScaleV, hScaleH;
GRAPH_DATA_Handle pdataGRP;
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    int NCode;
    int Id, i;
    struct exper_msg *priv;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Framewin'
        //
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_GRAY);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_GET);
        BUTTON_SetFont(hItem, &GUI_FontHZ_Consolas);
        BUTTON_SetTextColor(hItem, 0, GUI_BLUE);
        BUTTON_SetText(hItem, "吸液");
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PUT);
        BUTTON_SetFont(hItem, &GUI_FontHZ_Consolas);
        BUTTON_SetTextColor(hItem, 0, GUI_BLUE);
        BUTTON_SetText(hItem, "排液");
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RETURN);
        BUTTON_SetFont(hItem, &GUI_FontHZ_Consolas);
        BUTTON_SetTextColor(hItem, 0, GUI_BLUE);
        BUTTON_SetText(hItem, "返回");
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_START);
        BUTTON_SetFont(hItem, &GUI_FontHZ_Consolas);
        BUTTON_SetTextColor(hItem, 0, GUI_BLUE);
        BUTTON_SetText(hItem, "开始实验");
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetFont(hItem, &GUI_FontHZ_Consolas);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "NaCL浓度");
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetFont(hItem, &GUI_FontHZ_Consolas);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "AgNO3浓度");
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
        TEXT_SetFont(hItem, &GUI_FontHZ_Consolas);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "AgNO3用量");
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
        TEXT_SetFont(hItem, &GUI_FontHZ_Consolas);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "电极电位");
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
        TEXT_SetFont(hItem, &GUI_FontHZ_Consolas);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "溶液存量");

        hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
        PROGBAR_SetFont(hItem, GUI_FONT_24B_ASCII);
        PROGBAR_SetBarColor(hItem, 0, GUI_GREEN);
        PROGBAR_SetMinMax(hItem, 0, 100);
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
        TEXT_SetFont(hItem, &GUI_FontHZ_Consolas);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "实验进度");

        hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_TEST);
        PROGBAR_SetFont(hItem, GUI_FONT_24B_ASCII);
        PROGBAR_SetBarColor(hItem, 0, GUI_GREEN);
        PROGBAR_SetMinMax(hItem, 0, 100);
        

        hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
        GRAPH_SetBorder(hItem, 40, 3, 3, 30);
        GRAPH_SetGridVis(hItem, 1);
        GRAPH_SetGridFixedX(hItem, 1);
        GRAPH_SetGridDistY(hItem, 25);
        GRAPH_SetGridDistX(hItem, 50);
        hScaleV = GRAPH_SCALE_Create(3, GUI_TA_LEFT, GRAPH_SCALE_CF_VERTICAL, 25);
        GRAPH_SCALE_SetTextColor(hScaleV, GUI_RED);
        GRAPH_AttachScale(hItem, hScaleV);
        hScaleH = GRAPH_SCALE_Create(160, GUI_TA_HCENTER, GRAPH_SCALE_CF_HORIZONTAL, 50);
        GRAPH_SCALE_SetTextColor(hScaleH, GUI_DARKGREEN);
        GRAPH_AttachScale(hItem, hScaleH);
        pdataGRP = GRAPH_DATA_YT_Create(GUI_GREEN, 500, 0, 0);
        GRAPH_AttachData(hItem, pdataGRP);
        GRAPH_DATA_YT_SetOffY(pdataGRP, 20);
        GRAPH_DATA_YT_SetAlign(pdataGRP, GRAPH_ALIGN_LEFT);
        GRAPH_DATA_YT_Clear(pdataGRP);
        // USER END
        break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_BUTTON_GET: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
                for (i = 0; i <= 100; i++) {
                    PROGBAR_SetValue(hItem, i);
                    WM_Exec();
                    vTaskDelay(50);
                }
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_PUT: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
                for (i = 100; i >= 0; i--) {
                    PROGBAR_SetValue(hItem, i);
                    WM_Exec();
                    vTaskDelay(50);
                }
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_RETURN: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                printf("run main menu\r\n");
                g_ui_msg.msg = MSG_LOAD_UI_MENU;
                GUI_EndDialog(pMsg->hWin, 0);
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_START: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_START);
                BUTTON_SetText(hItem, "停止实验");
                msg.msg = EXPER_MSG_START;
                exper_msg_set(&msg);
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
    case WM_USER:
        priv = (struct exper_msg *)pMsg->Data.p;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_TEST);
        PROGBAR_SetValue(hItem, priv->progress);
        GRAPH_DATA_YT_AddValue(pdataGRP, (I16)(priv->progress & 0xffff));
        WM_Exec();
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/

WM_HWIN ui_blocktest_creat(void)
{
    g_ui_msg.hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    GUI_ExecCreatedDialog(g_ui_msg.hWin);
    return g_ui_msg.hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
