/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "main.h"
#include "experiment.h"
#include "stdio.h"
#include "FreeRTOS.h"
#include "task.h"
#include "beep.h"
#include "data.h"
#include "string.h"
#include "report.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_LISTVIEW_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_RETURN (GUI_ID_USER + 0x03)
#define ID_BUTTON_EXP (GUI_ID_USER + 0x04)
#define ID_BUTTON_PRINT (GUI_ID_USER + 0x05)

#define ID_TEXT_DATE (GUI_ID_USER + 0x06)

#define ID_TEXT_IDX (GUI_ID_USER + 0x07)
#define ID_TEXT_IDX_VALUE (GUI_ID_USER + 0x08)

#define ID_TEXT_XSYND (GUI_ID_USER + 0x09)
#define ID_TEXT_XSYND_VALUE (GUI_ID_USER + 0x0A)

#define ID_TEXT_KBSYXXYYL (GUI_ID_USER + 0x0B)
#define ID_TEXT_KBSYXXYYL_VALUE (GUI_ID_USER + 0x0C)

#define ID_TEXT_XSYYL (GUI_ID_USER + 0x0D)
#define ID_TEXT_XSYYL_VALUE (GUI_ID_USER + 0x0E)

#define ID_TEXT_MKSYHLLZ (GUI_ID_USER + 0x0F)
#define ID_TEXT_MKSYHLLZ_VALUE (GUI_ID_USER + 0x10)

#define ID_TEXT_PPM (GUI_ID_USER + 0x11)
#define ID_TEXT_PPM_VALUE (GUI_ID_USER + 0x12)

// USER START (Optionally insert additional defines)
extern const GUI_FONT GUI_FontHZ_kaiti_28;
extern const GUI_FONT GUI_FontHZ_kaiti_20;
extern GUI_CONST_STORAGE GUI_FONT GUI_FontArial24;

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    {WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0},
    {LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 5, 5, 420, 460, 0, 0x0, 0},
    
    //{BUTTON_CreateIndirect, "Button", ID_BUTTON_EXP, 660, 300, 100, 50, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "Button", ID_BUTTON_PRINT, 460, 300, 300, 60, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "Button", ID_BUTTON_RETURN, 460, 410, 300, 60, 0, 0x0, 0},

    {TEXT_CreateIndirect, "Text", ID_TEXT_DATE, 440, 10, 250, 25, 0, 0x64, 0},

    {TEXT_CreateIndirect, "Text", ID_TEXT_IDX, 440, 40, 50, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text", ID_TEXT_IDX_VALUE, 640, 40, 80, 25, 0, 0x64, 0},
    
    {TEXT_CreateIndirect, "硝酸银浓度", ID_TEXT_XSYND, 440, 70, 195, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text", ID_TEXT_XSYND_VALUE, 640, 70, 150, 25, 0, 0x64, 0},

    {TEXT_CreateIndirect, "空白实验用量", ID_TEXT_KBSYXXYYL, 440, 100, 250, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text", ID_TEXT_KBSYXXYYL_VALUE, 640, 100, 80, 25, 0, 0x64, 0},

    {TEXT_CreateIndirect, "硝酸银用量", ID_TEXT_XSYYL, 440, 130, 250, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text", ID_TEXT_XSYYL_VALUE, 640, 130, 80, 25, 0, 0x64, 0},
    
    {TEXT_CreateIndirect, "Text", ID_TEXT_MKSYHLLZ, 440, 160, 250, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text", ID_TEXT_MKSYHLLZ_VALUE, 640, 190, 150, 25, 0, 0x64, 0},

    {TEXT_CreateIndirect, "PPM", ID_TEXT_PPM, 440, 220, 250, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "Text", ID_TEXT_PPM_VALUE, 640, 220, 81, 25, 0, 0x64, 0},
    // USER START (Optionally insert additional widgets)
    // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
static struct result_data res;
static int index;
// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    int NCode;
    int Id;
    int i;
    unsigned row;
    char buf[32];
    HEADER_Handle hHeader;
    // USER START (Optionally insert additional variables)
    // USER END
    struct result_data *pres = &res;

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Framewin'
        //
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_GRAY);
        //
        // Initialization of 'Listview'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
        LISTVIEW_SetRowHeight(hItem, 25);
        LISTVIEW_SetBkColor(hItem, 0, GUI_GRAY);
        LISTVIEW_SetGridVis(hItem, 1);
        LISTVIEW_SetFont(hItem, GUI_FONT_24_ASCII);
        for (i = 0; i < 17; i++)
            LISTVIEW_AddRow(hItem, NULL);

        hHeader = LISTVIEW_GetHeader(hItem);
        HEADER_SetFont(hHeader, &GUI_FontArial24);
        HEADER_SetTextColor(hHeader, GUI_BLUE);
        HEADER_SetHeight(hHeader, 35);
        HEADER_SetBkColor(hHeader, GUI_GRAY);
        LISTVIEW_AddColumn(hItem, 120, "AgNO3/mL", GUI_TA_HCENTER | GUI_TA_VCENTER);
        LISTVIEW_AddColumn(hItem, 105, "V/mV", GUI_TA_HCENTER | GUI_TA_VCENTER);
        LISTVIEW_AddColumn(hItem, 105, "Δ/mV", GUI_TA_HCENTER | GUI_TA_VCENTER);
        LISTVIEW_AddColumn(hItem, 105, "Δ?/mV", GUI_TA_HCENTER | GUI_TA_VCENTER);
        
        LISTVIEW_SetTextColor(hItem, 0, GUI_BLACK);

        data_get(pres, index);

        row = 0;
        for (i = 0; i < pres->items_cnt; i++, row += 2) {
            sprintf(buf, "%.2f", pres->items[i].agno3_used);
            LISTVIEW_SetItemText(hItem, 0, row, buf);
            sprintf(buf, "%.1f", pres->items[i].volt);
            LISTVIEW_SetItemText(hItem, 1, row, buf);
        }

        row = 1;
        for (i = 1; i < pres->items_cnt; i++, row += 2) {
            sprintf(buf, "%.1f", pres->items[i].delta_v);
            LISTVIEW_SetItemText(hItem, 2, row, buf);
        }
            

        row = 2;
        for (i = 2; i < pres->items_cnt; i++, row += 2) {
            sprintf(buf, "%.1f", pres->items[i].delta2_v);
            LISTVIEW_SetItemText(hItem, 3, row, buf);
        }

        WM_DisableWindow(hItem);
            
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RETURN);
        BUTTON_SetFont(hItem, &GUI_FontHZ_kaiti_20);
        BUTTON_SetTextColor(hItem, 0, GUI_RED);
        BUTTON_SetText(hItem, "返回");
        //
        // Initialization of 'Button'
        //
        //hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_EXP);
        //BUTTON_SetFont(hItem, &GUI_FontHZ_kaiti_20);
        //BUTTON_SetTextColor(hItem, 0, GUI_BLUE);
        //BUTTON_SetText(hItem, "导出");
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PRINT);
        BUTTON_SetFont(hItem, &GUI_FontHZ_kaiti_20);
        BUTTON_SetTextColor(hItem, 0, GUI_BLUE);
        BUTTON_SetText(hItem, "打印");
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_IDX);
        TEXT_SetFont(hItem, &GUI_FontHZ_kaiti_20);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        TEXT_SetText(hItem, "序号");
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_IDX_VALUE);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        sprintf(buf, "%03d", pres->index);
        TEXT_SetText(hItem, buf);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_XSYND);
        TEXT_SetFont(hItem, &GUI_FontHZ_kaiti_20);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_XSYND_VALUE);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        sprintf(buf, "%.4fmol/L", pres->agno3_dosage);
        TEXT_SetText(hItem, buf);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_KBSYXXYYL);
        TEXT_SetFont(hItem, &GUI_FontHZ_kaiti_20);
        TEXT_SetTextColor(hItem, GUI_BLACK);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_KBSYXXYYL_VALUE);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        sprintf(buf, "%.2fmL", pres->block_agno3_used);
        TEXT_SetText(hItem, buf);

        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_DATE);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        sprintf(buf, "20%02d-%02d-%02d      %02d:%02d",
            pres->year, pres->month, pres->day, pres->hour, pres->minute);
        TEXT_SetText(hItem, buf);
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_XSYYL);
        TEXT_SetFont(hItem,  &GUI_FontHZ_kaiti_20);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        TEXT_SetText(hItem, "硝酸银用量");
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_XSYYL_VALUE);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        sprintf(buf, "%.2fmL", pres->cl_agno3_used);
        TEXT_SetText(hItem, buf);
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_MKSYHLLZ);
        TEXT_SetFont(hItem,  &GUI_FontHZ_kaiti_20);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        switch (pres->type) {
        case DATA_TYPE_STAND:
            TEXT_SetText(hItem, "氯离子浓度");
            break;
        case DATA_TYPE_EXTEST:
            TEXT_SetText(hItem, "试样氯离子质量分数");
            break;
        default:
            TEXT_SetText(hItem, "水泥氯离子质量分数");
            break;
        }
            
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_MKSYHLLZ_VALUE);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        if (pres->type == DATA_TYPE_STAND)
            sprintf(buf, "%fmol/L", pres->cl_dosage);
        else
            sprintf(buf, "%.3f%%", pres->cl_percentage);
        TEXT_SetText(hItem, buf);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_PPM);
        TEXT_SetFont(hItem,  &GUI_FontHZ_kaiti_20);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        switch (pres->type) {
        case DATA_TYPE_CL:
        case DATA_TYPE_EXTEST:
            WM_HideWindow(hItem);
            break;
        default:
            break;
        }
            
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_PPM_VALUE);
        TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
        TEXT_SetTextColor(hItem, GUI_BLACK);
        switch (pres->type) {
        case DATA_TYPE_STAND:
            sprintf(buf, "%.1f", pres->ppm);
            TEXT_SetText(hItem, buf);
            break;
        default:
            WM_HideWindow(hItem);
            break;
        }
        // USER START (Optionally insert additional code for further widget initialization)
        // USER END
        break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_LISTVIEW_0: // Notifications sent by 'Listview'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_RETURN: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                beep_clicked();
                g_ui_msg.msg = MSG_LOAD_UI_DATA;
                GUI_EndDialog(pMsg->hWin, 0);
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        //case ID_BUTTON_EXP: // Notifications sent by 'Button'
        //    switch (NCode)
        //    {
        //    case WM_NOTIFICATION_CLICKED:
        //        // USER START (Optionally insert code for reacting on notification message)
        //        beep_clicked();
        //        // USER END
        //        break;
        //    case WM_NOTIFICATION_RELEASED:
        //        // USER START (Optionally insert code for reacting on notification message)
        //        // USER END
        //        break;
        //        // USER START (Optionally insert additional code for further notification handling)
        //        // USER END
        //    }
        //    break;
        case ID_BUTTON_PRINT: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                beep_clicked();
                report_show(pres);
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/

int data_detail_creat(int item)
{
    index = item;
    return GUI_ExecDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
