/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "beep.h"
#include "main.h"
#include "string.h"
#include "stdio.h"
#include "experiment.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_0 (GUI_ID_USER + 0x03)
#define ID_TEXT_1 (GUI_ID_USER + 0x04)
#define ID_BUTTON_1 (GUI_ID_USER + 0x05)
#define ID_IMAGE_0 (GUI_ID_USER + 0x06)
#define ID_TEXT_2 (GUI_ID_USER + 0x07)

extern const GUI_FONT GUI_FontHZ_kaiti_20;
extern const GUI_BITMAP bminfor_32px;
extern const GUI_BITMAP bmwarning_32px;

static struct ui_exper_info ginfo;

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    {WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 150, 120, 500, 240, 0, 0x0, 0},
    {TEXT_CreateIndirect, "信息", ID_TEXT_0, 52, 14, 80, 25, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "开始实验", ID_BUTTON_0, 20, 185, 140, 40, 0, 0x0, 0},
    {TEXT_CreateIndirect, "line1", ID_TEXT_1, 10, 67, 466, 25, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "取消", ID_BUTTON_1, 340, 185, 140, 40, 0, 0x0, 0},
    {IMAGE_CreateIndirect, "Image", ID_IMAGE_0, 10, 10, 32, 32, 0, 0, 0},
    {TEXT_CreateIndirect, "line2", ID_TEXT_2, 10, 105, 462, 25, 0, 0x0, 0},
    // USER START (Optionally insert additional widgets)
    // USER END
};

static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    int NCode;
    int Id;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId) {
    case WM_INIT_DIALOG:
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_DARKBLUE);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
        BUTTON_SetFont(hItem, &GUI_FontHZ_kaiti_20);
        BUTTON_SetTextColor(hItem, 0, GUI_BLUE);
        switch (ginfo.func) {
        case EXPER_TYPE_CEMENT_SLIVER_NITRATE:
        case EXPER_TYPE_CEMENT_BLOCK:
        case EXPER_TYPE_CEMENT_CHLORIDE_ION:
        case EXPER_TYPE_OTHER_SLIVER_NITRATE:
        case EXPER_TYPE_OTHER_BLOCK:
        case EXPER_TYPE_OTHER_CHLORIDE_ION:
        case EXPER_TYPE_MANUAL_TITRATION:
        case EXPER_TYPE_ADMIXTURE_SLIVER_NITRATE1:
        case EXPER_TYPE_ADMIXTURE_BLOCK1:
        case EXPER_TYPE_ADMIXTURE_CHLORIDE_ION1:
        case EXPER_TYPE_ADMIXTURE_SLIVER_NITRATE2:
        case EXPER_TYPE_ADMIXTURE_BLOCK2:
        case EXPER_TYPE_ADMIXTURE_CHLORIDE_ION2:
            if (ginfo.flag)
                BUTTON_SetText(hItem, "停止实验");
            else
                BUTTON_SetText(hItem, "开始实验");
            break;
        case EXPER_TYPE_ADMIXTURE_SLIVER_NITRATE1_FINISHED:
        case EXPER_TYPE_ADMIXTURE_BLOCK1_FINISHED:
        case EXPER_TYPE_ADMIXTURE_CHLORIDE_ION1_FINISHED:
            BUTTON_SetText(hItem, "继续实验");
            break;
        case EXPER_MSG_OIL_CLEAR:
            BUTTON_SetText(hItem, "开始清洗");
            break;
        case DATA_MSG_DEL:
            BUTTON_SetText(hItem, "删除");
            break;
        case DATA_MSG_DEL_ALL:
            BUTTON_SetText(hItem, "全部删除");
            break;
        case INFO_ZSB_CALI:
            BUTTON_SetText(hItem, "开始校准");
            break;
        case INFO_DATA_EXPORT:
            BUTTON_SetText(hItem, "导出");
            break;
        case INFO_DJDW_CALC:
            BUTTON_SetText(hItem, "开始校准");
            break;
        default:
            break;
        }
      
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetFont(hItem, &GUI_FontHZ_kaiti_20);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        if (ginfo.flag)
            TEXT_SetText(hItem, "警告");
        else
            TEXT_SetText(hItem, "信息");

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
        BUTTON_SetFont(hItem, &GUI_FontHZ_kaiti_20);
        BUTTON_SetTextColor(hItem, 0, GUI_BLUE);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
        if (ginfo.flag)
            IMAGE_SetBitmap(hItem, &bmwarning_32px);
        else
            IMAGE_SetBitmap(hItem, &bminfor_32px);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetFont(hItem, &GUI_FontHZ_kaiti_20);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        if (ginfo.flag)
            TEXT_SetText(hItem, "实验正在进行中");
        else {
            switch (ginfo.func) {
            case EXPER_TYPE_CEMENT_SLIVER_NITRATE:
            case EXPER_TYPE_OTHER_SLIVER_NITRATE:
            case EXPER_TYPE_ADMIXTURE_SLIVER_NITRATE1:
                TEXT_SetText(hItem, "即将进行AgNO3浓度检测");
                break;
            case EXPER_TYPE_CEMENT_BLOCK:
            case EXPER_TYPE_OTHER_BLOCK:
            case EXPER_TYPE_ADMIXTURE_BLOCK1:
                TEXT_SetText(hItem, "即将进行空白实验");
                break;
            case EXPER_TYPE_CEMENT_CHLORIDE_ION:
            case EXPER_TYPE_ADMIXTURE_CHLORIDE_ION1:
                TEXT_SetText(hItem, "即将进行试样氯离子含量检测");
                break;
            case EXPER_TYPE_OTHER_CHLORIDE_ION:
                TEXT_SetText(hItem, "即将进行氯离子含量检测");
                break;
            case EXPER_TYPE_MANUAL_TITRATION:
                TEXT_SetText(hItem, "即将进行溶液滴定");
                break;
            case EXPER_MSG_OIL_CLEAR:
                TEXT_SetText(hItem, "即将进行检测仪自动清洗");
                break;
            case DATA_MSG_DEL:
                TEXT_SetText(hItem, "即将删除数据,删除后无法恢复");
                break;
            case DATA_MSG_DEL_ALL:
                TEXT_SetText(hItem, "即将删除所有数据，删除后无法恢复");
                break;
            case INFO_ZSB_CALI:
                TEXT_SetText(hItem, "即将进行注射泵行程校准");
                break;
            case INFO_DJDW_CALC:
                TEXT_SetText(hItem, "即将进行电极电位校准");
                break;
            case INFO_DATA_EXPORT:
                TEXT_SetText(hItem, "即将导出数据到U盘");
                break;
            case EXPER_TYPE_ADMIXTURE_SLIVER_NITRATE1_FINISHED:
            case EXPER_TYPE_ADMIXTURE_BLOCK1_FINISHED:
            case EXPER_TYPE_ADMIXTURE_CHLORIDE_ION1_FINISHED:
                TEXT_SetText(hItem, "请加入10mL 氯化钠标准溶液");
                break;
            default:
                break;
            }
        }

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
        TEXT_SetFont(hItem, &GUI_FontHZ_kaiti_20);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        switch (ginfo.func) {
        case EXPER_TYPE_CEMENT_BLOCK:
        case EXPER_TYPE_CEMENT_SLIVER_NITRATE:
        case EXPER_TYPE_CEMENT_CHLORIDE_ION:
        case EXPER_TYPE_OTHER_SLIVER_NITRATE:
        case EXPER_TYPE_OTHER_BLOCK:
        case EXPER_TYPE_OTHER_CHLORIDE_ION:
        case EXPER_TYPE_MANUAL_TITRATION:
        case EXPER_TYPE_ADMIXTURE_SLIVER_NITRATE1:
        case EXPER_TYPE_ADMIXTURE_SLIVER_NITRATE2:
        case EXPER_TYPE_ADMIXTURE_BLOCK1:
        case EXPER_TYPE_ADMIXTURE_BLOCK2:
        case EXPER_TYPE_ADMIXTURE_CHLORIDE_ION1:
        case EXPER_TYPE_ADMIXTURE_CHLORIDE_ION2:
            if (ginfo.flag)
                TEXT_SetText(hItem, "确定停止实验吗?");
            else
                TEXT_SetText(hItem, "确定开始实验吗?");
            break;
        case EXPER_TYPE_ADMIXTURE_SLIVER_NITRATE1_FINISHED:
        case EXPER_TYPE_ADMIXTURE_BLOCK1_FINISHED:
        case EXPER_TYPE_ADMIXTURE_CHLORIDE_ION1_FINISHED:
            TEXT_SetText(hItem, "加入完成后, 点击继续实验");
            break;
        case EXPER_MSG_OIL_CLEAR:
            TEXT_SetText(hItem, "确定开始清洗吗?");
            break;
        case DATA_MSG_DEL:
            TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
            TEXT_SetText(hItem, ginfo.str);
            break;
        case DATA_MSG_DEL_ALL:
            TEXT_SetText(hItem, "请谨慎操作");
            break;
        case INFO_ZSB_CALI:
            TEXT_SetText(hItem, "请根据说明书谨慎操作");
            break;
        case INFO_DJDW_CALC:
            TEXT_SetText(hItem, "请短接电极正负输入后点击校准按钮");
            break;
        case INFO_DATA_EXPORT:
            TEXT_SetText(hItem, "请确保U盘插入");
            break;
        default:
            break;
        }
        break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_BUTTON_0: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                beep_clicked();
                GUI_EndDialog(pMsg->hWin, 0);
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_1: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                beep_clicked();
                GUI_EndDialog(pMsg->hWin, 1);
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

int diag_info_creat(struct ui_exper_info *info)
{
    memcpy(&ginfo, info, sizeof(struct ui_exper_info));
    return GUI_ExecDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
